### ISSUE TITLE
Exception ignored in: <function MjRenderContext.__del__ at 0x7fc012e07790>

### ISSUE THREAD

**Issue by dzy666fly** [hengyuan-hu/ibrl#5]
Thank u for sharing this wonderful work!
When I try to reproduce the result with the command`python train_rl.py --config_path release/cfgs/robomimic_rl/square_ibrl.yaml
`, the result in the wandb seems to be reasonable. But in the shell it shows error as follows, I am not sure whether it will influence the result.
```
Exception ignored in: <function MjRenderContext.__del__ at 0x7fc012e07790>
Traceback (most recent call last):
  File "/home/.../Code/Source/ibrl/robosuite/robosuite/utils/binding_utils.py", line 199, in __del__
    self.gl_ctx.free()
  File "/home/.../Code/Source/ibrl/robosuite/robosuite/renderers/context/egl_context.py", line 149, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "/home/.../Softwares/anaconda3/envs/ibrl/lib/python3.9/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglMakeCurrent,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7fc0054d0e40>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x7fc013008840>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x7fc013008840>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7fc013008540>,
	),
	result = 0
)
```
Well, owing to the unstable Internet connection, the package `robosuitev1.4.1` is downloaded directly with the link 'https://codeload.github.com/ARISE-Initiative/robosuite/zip/refs/heads/v1.4.1', and then use ```pip install -e .```.  I am not sure maybe it is the reason.
Looking forward to ur reply.

**Comment by hengyuan-hu** [comment]
This is normal, caused by improper cleaning up in the robosuite library. I added a few try-except in robosuite code to silence it but it is totally ok to leave it as it is if it does not bother you.

**Comment by dzy666fly** [comment]
Thank u so much.
